project:
  type: book
  output-dir: _output

book:
  title: "Research Manuscript"
  chapters:
    - index.md
    - docs/Introduction.md
    - docs/Methods.md
    - docs/Results.md
    - docs/Discussion.md
    - docs/References.qmd

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    pdf-engine: xelatex
    keep-tex: false
    geometry: margin=2.5cm

bibliography: ../references/references.bib
csl: https://www.zotero.org/styles/nature