project:
  type: book
  output-dir: _output

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    pdf-engine: xelatex
    keep-tex: false
    geometry: margin=2.5cm
    
book:
  title: "My Experiment"
  author: "Your Name"
  date: today
  chapters:
    - index.md
    - part: "Study Design"
      chapters:
        - design/Scientific_Context.md
        - design/Protocol.md

    - part: "Manuscript"
      chapters:
        - manuscript/Introduction.md
        - manuscript/Methods.md
        - manuscript/Results.md
        - manuscript/Discussion.md

    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/nature